# Generated by Django 5.1.4 on 2026-06-25 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_id', models.CharField(db_index=True, max_length=80)),
                ('run_id', models.CharField(max_length=40)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-finished_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheckException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('enters', 'Оприходования на внутренних складах'), ('losses', 'Списания'), ('inventories', 'Инвентаризации'), ('moves', 'Перемещения'), ('supplies', 'Приёмки'), ('salesreturns', 'Возвраты от покупателей'), ('enter_zero', 'Оприходования с нулевой ценой'), ('deviations', 'Отклонения FIFO vs приёмка'), ('supply_jumps', 'Скачки цен в приёмках')], max_length=20)),
                ('key', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='userpageevent',
            new_name='api_userpag_user_id_48f2b1_idx',
            old_name='api_userpa_user_id_idx',
        ),
        migrations.AddIndex(
            model_name='checkrunresult',
            index=models.Index(fields=['script_id', '-finished_at'], name='api_checkru_script__6fd48b_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkrunresult',
            constraint=models.UniqueConstraint(fields=('script_id', 'run_id'), name='uniq_checkrun_result'),
        ),
        migrations.AddField(
            model_name='healthcheckexception',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_check_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='healthcheckexception',
            index=models.Index(fields=['kind'], name='api_healthc_kind_5f25cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthcheckexception',
            constraint=models.UniqueConstraint(fields=('kind', 'key'), name='uniq_healthcheck_exception'),
        ),
    ]
