# Generated by Django 5.1.4 on 2026-09-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notificationstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdekWaybillState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='Заказ в МойСклад')),
                ('payload', models.JSONField(default=dict, verbose_name='Запись робота')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Накладная СДЭК (состояние робота)',
                'verbose_name_plural': 'Накладные СДЭК (состояние робота)',
            },
        ),
    ]
