# Generated by Django 5.1.4 on 2026-09-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cdekwaybillstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOrderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='Заказ на сайте')),
                ('date', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Дата заказа')),
                ('payload', models.JSONField(default=dict, verbose_name='Заказ целиком')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Заказ сайта (копия выгрузки)',
                'verbose_name_plural': 'Заказы сайта (копия выгрузки)',
            },
        ),
        migrations.CreateModel(
            name='SiteOrdersReconcileState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetch', models.CharField(blank=True, max_length=32, verbose_name='Последняя выгрузка')),
                ('last_acknowledge', models.CharField(blank=True, max_length=32, verbose_name='Последнее подтверждение')),
            ],
            options={
                'verbose_name': 'Сверка заказов сайта (отметки)',
                'verbose_name_plural': 'Сверка заказов сайта (отметки)',
            },
        ),
    ]
