# Generated by Django 5.1.4 on 2026-09-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_site_orders_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPriceSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32, unique=True, verbose_name='Когда')),
                ('stats', models.JSONField(default=dict, verbose_name='Счётчики')),
                ('changes', models.JSONField(default=list, verbose_name='Что изменилось')),
                ('errors', models.JSONField(default=list, verbose_name='Ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Записан')),
            ],
            options={
                'verbose_name': 'Прогон робота закупочных цен',
                'verbose_name_plural': 'Прогоны робота закупочных цен',
                'ordering': ['-date'],
            },
        ),
    ]
