# Generated by Django 5.1.4 on 2026-09-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_buy_price_sync_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnProcessedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='Заказ в МойСклад')),
                ('payload', models.JSONField(default=dict, verbose_name='Отметка разбора')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Разобранный возврат',
                'verbose_name_plural': 'Разобранные возвраты',
            },
        ),
        migrations.CreateModel(
            name='ReturnsMonitorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run', models.CharField(blank=True, max_length=32, verbose_name='Последний прогон')),
            ],
            options={
                'verbose_name': 'Монитор возвратов (отметка)',
                'verbose_name_plural': 'Монитор возвратов (отметка)',
            },
        ),
    ]
