# Generated by Django 5.1.4 on 2026-09-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_returns_monitor_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=500, unique=True, verbose_name='Message-ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Разобрано')),
            ],
            options={
                'verbose_name': 'Разобранное письмо о заказе',
                'verbose_name_plural': 'Разобранные письма о заказах',
            },
        ),
        migrations.CreateModel(
            name='OrderEmailOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='Номер на сайте')),
                ('payload', models.JSONField(default=dict, verbose_name='Заказ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Заказ сайта из писем',
                'verbose_name_plural': 'Заказы сайта из писем',
            },
        ),
        migrations.CreateModel(
            name='OrderEmailState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_date', models.CharField(blank=True, max_length=32, verbose_name='Последняя проверенная дата')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Робот писем (отметки)',
                'verbose_name_plural': 'Робот писем (отметки)',
            },
        ),
    ]
