# Generated by Django 5.1.4 on 2026-09-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_order_email_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDeadlineSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict, verbose_name='Снимок')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Собран')),
            ],
            options={
                'verbose_name': 'Сроки оплаты (снимок)',
                'verbose_name_plural': 'Сроки оплаты (снимок)',
            },
        ),
    ]
