# Generated by Django 5.1.13 on 2026-09-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_payment_deadline_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Раздел')),
                ('payload', models.JSONField(default=dict, verbose_name='Снимок')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Собран')),
            ],
            options={
                'verbose_name': 'Снимок раздела',
                'verbose_name_plural': 'Снимки разделов',
            },
        ),
    ]
