# Generated by Django 5.1.4 on 2026-08-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=255, unique=True, verbose_name='Артикул (offer_id)')),
                ('sku', models.BigIntegerField(verbose_name='SKU в Ozon')),
                ('product_id', models.BigIntegerField(blank=True, null=True, verbose_name='product_id в Ozon')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Название')),
                ('has_fbs_stocks', models.BooleanField(default=False, verbose_name='Есть остатки FBS')),
                ('has_fbo_stocks', models.BooleanField(default=False, verbose_name='Есть остатки FBO')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено из Ozon')),
            ],
            options={
                'verbose_name': 'Товар Ozon',
                'verbose_name_plural': 'Товары Ozon',
                'ordering': ['offer_id'],
                'indexes': [models.Index(fields=['sku'], name='ozon_logist_sku_9ce5ba_idx')],
            },
        ),
    ]
