# Generated by Django 5.1.4 on 2026-08-31 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_logistics', '0002_ozonproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonPickupPoint',
            fields=[
                ('map_point_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID точки на карте')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=1000, verbose_name='Адрес')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Подробности из Ozon')),
                ('details_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Подробности обновлены')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Координаты обновлены')),
            ],
            options={
                'verbose_name': 'Пункт выдачи Ozon',
                'verbose_name_plural': 'Пункты выдачи Ozon',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='ozon_logist_latitud_02e76e_idx')],
            },
        ),
    ]
