# Generated by Django 5.1.4 on 2026-08-31 17:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_logistics', '0003_ozonpickuppoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonDeliveryQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон покупателя')),
                ('items', models.JSONField(verbose_name='Состав: sku и количество')),
                ('map_point_id', models.BigIntegerField(blank=True, null=True, verbose_name='Пункт выдачи')),
                ('courier_address', models.JSONField(blank=True, null=True, verbose_name='Адрес курьерской доставки')),
                ('checkout_response', models.JSONField(verbose_name='Ответ Ozon на расчёт')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость логистики, ₽')),
                ('status', models.CharField(choices=[('new', 'Рассчитан'), ('ordered', 'Заказ создан в Ozon'), ('failed', 'Ошибка создания')], default='new', max_length=16, verbose_name='Статус')),
                ('site_order_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Заказ сайта')),
                ('order_number', models.CharField(blank=True, max_length=64, verbose_name='Номер заказа в Ozon')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка создания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordered_at', models.DateTimeField(blank=True, null=True, verbose_name='Заказ создан')),
            ],
            options={
                'verbose_name': 'Расчёт доставки Ozon',
                'verbose_name_plural': 'Расчёты доставки Ozon',
                'ordering': ['-created_at'],
            },
        ),
    ]
