# Generated by Django 5.1.4 on 2026-08-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_logistics', '0004_ozondeliveryquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozondeliveryquote',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Попыток создания'),
        ),
        migrations.AlterField(
            model_name='ozondeliveryquote',
            name='status',
            field=models.CharField(choices=[('new', 'Рассчитан'), ('ordered', 'Заказ создан в Ozon'), ('failed', 'Ошибка создания'), ('unknown', 'Исход неизвестен — проверьте в Ozon')], default='new', max_length=16, verbose_name='Статус'),
        ),
    ]
