# Generated by Django 5.1.4 on 2026-09-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_logistics', '0005_ozondeliveryquote_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozondeliveryquote',
            name='postings',
            field=models.JSONField(blank=True, null=True, verbose_name='Номера отправлений'),
        ),
        migrations.CreateModel(
            name='OzonPosting',
            fields=[
                ('posting_number', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Номер отправления')),
                ('order_number', models.CharField(db_index=True, max_length=64, verbose_name='Номер заказа Ozon')),
                ('schema', models.CharField(choices=[('fbs', 'FBS — наш склад'), ('fbo', 'FBO — склад Ozon')], max_length=8, verbose_name='Схема')),
                ('status', models.CharField(blank=True, max_length=64, verbose_name='Статус')),
                ('cancel_reason', models.CharField(blank=True, max_length=500, verbose_name='Причина отмены')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Ответ Ozon')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отработано человеком')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings_tracked', to='ozon_logistics.ozondeliveryquote', verbose_name='Расчёт')),
            ],
            options={
                'verbose_name': 'Отправление Ozon',
                'verbose_name_plural': 'Отправления Ozon',
                'ordering': ['-created_at'],
            },
        ),
    ]
