# Generated by Django 5.1.4 on 2026-09-01 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_logistics', '0006_ozondeliveryquote_postings_ozonposting'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonReturn',
            fields=[
                ('return_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='ID возврата в Ozon')),
                ('posting_number', models.CharField(db_index=True, max_length=64, verbose_name='Отправление')),
                ('order_number', models.CharField(blank=True, max_length=64, verbose_name='Заказ Ozon')),
                ('return_type', models.CharField(blank=True, max_length=32, verbose_name='Тип возврата')),
                ('schema', models.CharField(blank=True, max_length=16, verbose_name='Схема')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='Причина')),
                ('status_name', models.CharField(blank=True, max_length=200, verbose_name='Статус')),
                ('status_sys_name', models.CharField(blank=True, max_length=100, verbose_name='Системный статус')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Ответ Ozon')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отработано человеком')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='ozon_logistics.ozondeliveryquote', verbose_name='Расчёт')),
            ],
            options={
                'verbose_name': 'Возврат Ozon',
                'verbose_name_plural': 'Возвраты Ozon',
                'ordering': ['-created_at'],
            },
        ),
    ]
