# Generated by Django 5.1.4 on 2026-09-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_logistics', '0007_ozonreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozonposting',
            name='duplicates_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дубли МойСклад проверены'),
        ),
    ]
