# Generated by Django 5.1.4 on 2026-09-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_logistics', '0008_ozonposting_duplicates_checked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonAvailabilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(db_index=True, verbose_name='Доставка доступна')),
                ('phone_mask', models.CharField(max_length=20, verbose_name='Телефон (маска)')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP покупателя')),
                ('referer', models.CharField(blank=True, max_length=200, verbose_name='Страница')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
            ],
            options={
                'verbose_name': 'Проверка доступности Ozon',
                'verbose_name_plural': 'Проверки доступности Ozon',
                'ordering': ['-created_at'],
            },
        ),
    ]
