# Generated by Django 5.1.13 on 2026-09-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_logistics', '0009_ozonavailabilitycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozondeliveryquote',
            name='ms_note',
            field=models.TextField(blank=True, verbose_name='Записано в заказ МойСклада'),
        ),
    ]
