# Generated by Django 5.1.13 on 2026-09-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_logistics', '0010_ozondeliveryquote_ms_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozondeliveryquote',
            name='ms_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заказ МойСклада проверен'),
        ),
        migrations.AddField(
            model_name='ozondeliveryquote',
            name='ms_shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отгрузка в МойСкладе закрыта'),
        ),
    ]
