# Generated by Django 5.1.13 on 2026-09-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_logistics', '0011_ozondeliveryquote_ms_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozondeliveryquote',
            name='ms_return',
            field=models.CharField(blank=True, max_length=64, verbose_name='Возврат от Озона'),
        ),
    ]
