# Generated by Django 5.1.4 on 2026-05-02 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('month_start', models.DateField()),
                ('total_products', models.IntegerField(default=0)),
                ('inventoried_count', models.IntegerField(default=0)),
                ('not_inventoried_count', models.IntegerField(default=0)),
                ('is_month_snapshot', models.BooleanField(default=False)),
                ('triggered_by', models.CharField(default='scheduler', max_length=20)),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInventoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('article', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('folder', models.CharField(max_length=100)),
                ('is_inventoried', models.BooleanField()),
                ('inventory_count', models.IntegerField(default=0)),
                ('last_inventoried_at', models.DateTimeField(blank=True, null=True)),
                ('days_since_last', models.IntegerField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory_tracking.inventoryrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'is_inventoried'], name='inventory_t_run_id_183c52_idx'), models.Index(fields=['run', 'folder'], name='inventory_t_run_id_f0ecd9_idx')],
            },
        ),
    ]
