# Generated by Django 5.1 on 2024-11-15 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование контрагента (покупателя)')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний ID')),
            ],
            options={
                'verbose_name': 'Контрагент (покупатель)',
                'verbose_name_plural': 'Контрагенты (покупатели)',
            },
        ),
        migrations.CreateModel(
            name='ProcessingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Техкарта',
                'verbose_name_plural': 'Техкарты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний ID')),
                ('uom_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения')),
                ('uom_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание единицы измерения')),
                ('group', models.CharField(blank=True, choices=[('ТАРА', 'Тара'), ('МАТЕРИАЛЫ', 'Материалы для производства'), ('ЭТИКЕТКИ', 'Этикетки')], max_length=50, null=True, verbose_name='Группа')),
                ('article', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Готовый продукт',
                'verbose_name_plural': 'Готовые продукты',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний ID')),
                ('uom_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения')),
                ('uom_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание единицы измерения')),
                ('group', models.CharField(blank=True, choices=[('ТАРА', 'Тара'), ('МАТЕРИАЛЫ', 'Материалы для производства'), ('ЭТИКЕТКИ', 'Этикетки')], max_length=50, null=True, verbose_name='Группа')),
                ('article', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сырьё',
                'verbose_name_plural': 'Сырьё',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер отгрузки')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.counterparty', verbose_name='Контрагент (покупатель)')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.product', verbose_name='Продукт')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parser.shipment', verbose_name='Отгрузка')),
            ],
            options={
                'verbose_name': 'Позиция отгрузки',
                'verbose_name_plural': 'Позиции отгрузки',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.rawmaterial', verbose_name='Сырьё')),
                ('shipment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_usages', to='parser.shipmentitem', verbose_name='Позиция отгрузки')),
            ],
            options={
                'verbose_name': 'Использование сырья',
                'verbose_name_plural': 'Использование сырья',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.counterparty', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Приемка',
                'verbose_name_plural': 'Приемки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.rawmaterial', verbose_name='Материал')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parser.supply', verbose_name='Приемка')),
            ],
            options={
                'verbose_name': 'Позиция приемки',
                'verbose_name_plural': 'Позиции приемки',
            },
        ),
        migrations.CreateModel(
            name='ProcessingPlanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('processing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='parser.processingplan', verbose_name='Техкарта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт техкарты',
                'verbose_name_plural': 'Продукты техкарты',
                'unique_together': {('processing_plan', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProcessingPlanMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('processing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='parser.processingplan', verbose_name='Техкарта')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.rawmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал техкарты',
                'verbose_name_plural': 'Материалы техкарты',
                'unique_together': {('processing_plan', 'material')},
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['date'], name='parser_ship_date_88a116_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['number'], name='parser_ship_number_4e3ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['shipment', 'product'], name='parser_ship_shipmen_249687_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialusage',
            index=models.Index(fields=['shipment_item', 'raw_material'], name='parser_rawm_shipmen_169635_idx'),
        ),
    ]
