# Generated by Django 5.1 on 2024-11-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_shipmentitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subgroup',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(blank=True, choices=[('ТАРА', 'Тара'), ('ПРОБНИКИ', 'Пробники'), ('МАТЕРИАЛЫ', 'Материалы для производства'), ('ТОВАРЫ', 'Товары'), ('ЭТИКЕТКИ', 'Этикетки')], max_length=50, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='group',
            field=models.CharField(blank=True, choices=[('ТАРА', 'Тара'), ('ПРОБНИКИ', 'Пробники'), ('МАТЕРИАЛЫ', 'Материалы для производства'), ('ТОВАРЫ', 'Товары'), ('ЭТИКЕТКИ', 'Этикетки')], max_length=50, null=True, verbose_name='Группа'),
        ),
    ]
