# Generated by Django 5.1 on 2024-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_product_subgroup_alter_product_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['group', 'subgroup', 'name'], 'verbose_name': 'Готовый продукт', 'verbose_name_plural': 'Готовые продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(blank=True, choices=[('Тара', 'Тара'), ('Пробники', 'Пробники'), ('Материалы для производства', 'Материалы для производства'), ('Товары', 'Товары'), ('Этикетки', 'Этикетки')], max_length=50, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='group',
            field=models.CharField(blank=True, choices=[('Тара', 'Тара'), ('Пробники', 'Пробники'), ('Материалы для производства', 'Материалы для производства'), ('Товары', 'Товары'), ('Этикетки', 'Этикетки')], max_length=50, null=True, verbose_name='Группа'),
        ),
    ]
