# Generated by Django 5.1 on 2024-11-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_alter_product_options_alter_product_group_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['group'], name='parser_prod_group_d2736a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['group', 'subgroup'], name='parser_prod_group_d9292b_idx'),
        ),
    ]
