# Generated by Django 5.1 on 2024-11-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_product_parser_prod_group_d2736a_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['group', 'subgroup', 'name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'verbose_name': 'Материал для производства', 'verbose_name_plural': 'Материалы для производства'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterialusage',
            options={'verbose_name': 'Использование материала для производства', 'verbose_name_plural': 'Использование материалов для производства'},
        ),
    ]
