# Generated by Django 5.1 on 2024-12-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_alter_product_options_alter_rawmaterial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingplan',
            name='moysklad_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обновлено в МойСклад'),
        ),
    ]
