# Generated by Django 5.1 on 2024-12-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0007_processingplan_moysklad_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='moysklad_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обновлено в МойСклад'),
        ),
        migrations.AddField(
            model_name='supply',
            name='moysklad_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обновлено в МойСклад'),
        ),
    ]
