# Generated by Django 5.1 on 2024-12-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0008_shipment_moysklad_updated_supply_moysklad_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='Отметьте, если это старая версия существующего контрагента', verbose_name='Старый контрагент'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='main_counterparty',
            field=models.ForeignKey(blank=True, help_text='Укажите основную версию контрагента, если это старая версия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_records', to='parser.counterparty', verbose_name='Основной контрагент'),
        ),
    ]
