# Generated by Django 5.1 on 2024-12-20 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0009_counterparty_is_legacy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер заказа')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('created', models.DateTimeField(verbose_name='Дата создания')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('moysklad_updated', models.DateTimeField(blank=True, null=True, verbose_name='Обновлено в МойСклад')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.counterparty', verbose_name='Поставщик')),
                ('supplies', models.ManyToManyField(blank=True, related_name='purchase_orders', to='parser.supply', verbose_name='Связанные приемки')),
            ],
            options={
                'verbose_name': 'Заказ поставщику',
                'verbose_name_plural': 'Заказы поставщикам',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('shipped_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Принято')),
                ('waiting_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='В ожидании')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parser.purchaseorder', verbose_name='Заказ поставщику')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.rawmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Позиция заказа поставщику',
                'verbose_name_plural': 'Позиции заказа поставщику',
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['date'], name='parser_purc_date_d70cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['created'], name='parser_purc_created_72dee0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='parser_purc_status_1d5c59_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order', 'raw_material'], name='parser_purc_purchas_1b762a_idx'),
        ),
    ]
