# Generated by Django 5.1 on 2024-12-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0010_purchaseorder_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['date', 'counterparty'], name='parser_ship_date_a99af4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['product'], name='parser_ship_product_cff5d6_idx'),
        ),
    ]
