# Generated by Django 5.1 on 2024-12-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0011_shipment_parser_ship_date_a99af4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rawmaterialusage',
            name='parser_rawm_shipmen_169635_idx',
        ),
        migrations.AddIndex(
            model_name='rawmaterial',
            index=models.Index(fields=['group'], name='parser_rawm_group_2767a3_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialusage',
            index=models.Index(fields=['raw_material', 'shipment_item'], name='parser_rawm_raw_mat_4371d8_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialusage',
            index=models.Index(fields=['shipment_item'], name='parser_rawm_shipmen_628013_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialusage',
            index=models.Index(fields=['raw_material'], name='parser_rawm_raw_mat_491235_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialusage',
            index=models.Index(fields=['quantity'], name='parser_rawm_quantit_a5ce9d_idx'),
        ),
    ]
