# Generated by Django 5.1 on 2024-12-17 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),  # Depends on core having Counterparty model
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('large', 'Крупный'), ('medium', 'Средний'), ('small', 'Мелкий'), ('rare_large', 'Редкий крупный')], max_length=20)),
                ('average_monthly_sales', models.DecimalField(decimal_places=2, help_text='Среднемесячный объем продаж', max_digits=12)),
                ('sales_frequency', models.FloatField(help_text='Частота продаж (доля месяцев с продажами)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('counterparty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_category', to='core.counterparty')),
            ],
            options={
                'verbose_name': 'Категория контрагента',
                'verbose_name_plural': 'Категории контрагентов',
            },
        ),
    ]
