# Generated by Django 5.1.4 on 2026-08-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounterpartyCategory',
        ),
    ]
