# Generated by Django 5.1.4 on 2026-01-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='lead_time_period_months',
            field=models.IntegerField(blank=True, help_text='Если не задано — используется 12 месяцев', null=True, verbose_name='Период расчёта времени доставки (мес)'),
        ),
    ]
