# Generated by Django 5.1.4 on 2026-08-26 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_synclock_lock_token'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rawmaterialusage',
            name='parser_rawm_quantit_a5ce9d_idx',
        ),
        migrations.AlterField(
            model_name='rawmaterialusage',
            name='raw_material',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial', verbose_name='Сырьё'),
        ),
        migrations.AlterField(
            model_name='rawmaterialusage',
            name='shipment_item',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_usages', to='core.shipmentitem', verbose_name='Позиция отгрузки'),
        ),
    ]
