# Generated by Django 5.1.4 on 2026-09-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_drop_unused_rawmaterialusage_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Канал продаж',
                'verbose_name_plural': 'Каналы продаж',
                'db_table': 'parser_saleschannel',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='sales_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='core.saleschannel', verbose_name='Канал продаж'),
        ),
    ]
