# Generated by Django 5.1.4 on 2026-09-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_saleschannel_shipment_sales_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Идёт'), ('completed', 'Завершён'), ('error', 'Ошибка'), ('stopped', 'Остановлен')], default='running', max_length=20, verbose_name='Статус')),
                ('stop_requested', models.BooleanField(default=False, verbose_name='Запрошена остановка')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Этап')),
                ('processed', models.PositiveSmallIntegerField(default=0, verbose_name='Готово, %')),
                ('total', models.PositiveSmallIntegerField(default=100, verbose_name='Всего, %')),
                ('triggered_by', models.CharField(blank=True, max_length=50, verbose_name='Кто запустил')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начат')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
            ],
            options={
                'verbose_name': 'Прогон синхронизации',
                'verbose_name_plural': 'Прогоны синхронизации',
                'db_table': 'parser_syncrun',
                'indexes': [models.Index(fields=['-started_at'], name='parser_sync_started_4d2846_idx')],
            },
        ),
    ]
