# Generated by Django 5.1.4 on 2026-09-07 08:38

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_syncrun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterialusage',
            options={'base_manager_name': 'all_objects', 'verbose_name': 'Использование материала для производства', 'verbose_name_plural': 'Использование материалов для производства'},
        ),
        migrations.AlterModelManagers(
            name='rawmaterialusage',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'base_manager_name': 'all_objects', 'verbose_name': 'Отгрузка', 'verbose_name_plural': 'Отгрузки'},
        ),
        migrations.AlterModelOptions(
            name='shipmentitem',
            options={'base_manager_name': 'all_objects', 'verbose_name': 'Позиция отгрузки', 'verbose_name_plural': 'Позиции отгрузки'},
        ),
        migrations.AlterModelManagers(
            name='shipment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='shipmentitem',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Пропала из выгрузки'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний раз в выгрузке'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['deleted_at'], name='parser_ship_deleted_0335ed_idx'),
        ),
    ]
