# Generated by Django 5.1.13 on 2026-09-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sync_entity_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='ID строки в МойСклад'),
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='ID строки в МойСклад'),
        ),
    ]
