# Generated by Django 5.1.13 on 2026-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shipmentitem_external_id_supplyitem_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Цена'),
        ),
    ]
